---
- hosts: 192.168.122.173
  become_user: root
  tasks:
    - name: install apache2
      become: yes
      apt: name=apache2 update_cache=yes state=latest
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      become: yes
      service: name=apache2 state=restarted
