---
- hosts: 192.168.122.248
  become: true
  become_user: root

  tasks:
    - name: Disable Maintenance Mode By Rm File
      file:
        path: "/var/www/html/maintenance.enable"
        state: absent
