---
- hosts: 192.168.122.110
  become_user: root

  tasks:
    - name: Disable Maintenance Mode By Rm File
      file:
        path: "/var/www/html/awx/public/maintenance.enable"
        state: absent

