---
- hosts: 192.168.122.110
  become_user: root

  tasks:
    - name: Enable Maintenance Mode By Touching File
      file: 
        path: "/var/www/html/awx/public/maintenance.enable"
        state: touch
