---
- hosts: 192.168.122.248 
  tasks:
  - name: Upgrade all packages for Debian VM & Install LAMP 
    apt:
     name: "*"
     state: latest
     update_cache: yes
     force_apt_get: yes

  - name: Install LAMP Packages
    apt: name={{ item }} update_cache=yes state=latest
    loop: [ 'mysql-server', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php' ]
