---
- hosts: 192.168.122.148
- name: Laravel Installation (Front & Back End)
  remote_user: root
 
  tasks: 
    - name: Install Apache
      become: yes
      apt: name=apache2 update_cache=yes state=latest
   
    - name: Install PHP & All PHP Dependencies
      become: yes 
      apt:
       name: '{{ packages }}'
       state: latest
       update_cache: yes
      vars:
        packages:
          - php
          - libapache2-mod-php
          - php-mbstring
          - php-xmlrpc
          - php-soap
          - php-gd
          - php-xml
          - php-cli 
          - php-zip
          - php-bcmath 
          - php-tokenizer 
          - php-json
          - php-pear

    - name: Install Database (Maria-DB)
      become: yes 
      apt: name=mariadb-server update_cache=yes state=latest

   - name: Install Curl 
     become: yes 
     apt: name=curl update_cache=yes state=latest

   - name: Install Composer 
     become: yes 
     ansible.builtin.command: curl -sS https://getcomposer.org/installer | php

   - name: Move Composer 
     become: yes 
     ansible.builtin.command: sudo mv composer.phar /usr/local/bin/composer 

   - name: Config Composer 
     become: yes 
     ansible.builtin.command: sudo chmod +x /usr/local/bin/composer

   - name: Create Laravel Project 
     become: yes 
     ansible.builtin.command: composer create-project --prefer-dist laravel/laravel test 
