---
- hosts: all
 
  become: yes
 
  vars:
    ansible_sudo_pass: "{{'password'}}"
   
  tasks:
    - name: Ping Host
      become: yes 
      ansible.builtin.command: ansible -i hosts -m ping 192.168.122.81
