---
  hosts: 192.168.122.110
  become_user: root
  become: yes
  
  tasks:
    - name: Update System
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes
        
